practicaRecSysG2/practicaRecSysG2/urls.py
from django.contrib import admin
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index),
    path('populate', views.populateDB),
    path('loadRS', views.loadRS),
    path('search', views.search),
    path('topThree', views.topThree),
    path('similarBooks', views.similarBooks),
    path('recommendedBooks', views.recommendedBooks),
    path('admin/', admin.site.urls),
]

practicaRecSysG2/main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class User(models.Model):
    
    def __str__(self):
        return str(self.id)
    
    
class Book(models.Model):
    ISBN = models.CharField(max_length = 100, primary_key = True)
    title = models.CharField(max_length = 100)
    author = models.CharField(max_length = 50)
    publicationYear = models.CharField(max_length = 4)
    publisher = models.CharField(max_length = 50)
    ratings = models.ManyToManyField(User, through = "Rating")
    
    def __str__(self):
        return self.title
    
    
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    book = models.ForeignKey(Book, on_delete = models.CASCADE)
    ratingValue = models.PositiveSmallIntegerField(validators = [MinValueValidator(1), MaxValueValidator(10)])
    
    def __str__(self):
        return str(self.ratingValue)

practicaRecSysG2/main/forms.py
from django import forms

class UserForm(forms.Form):
    id = forms.CharField(label = "User ID")

    
class BookForm(forms.Form):
    isbn = forms.CharField(label = "Book ISBN")

practicaRecSysG2/main/views.py
import shelve
from django.shortcuts import render, get_object_or_404
from main.populate import populateDatabase
from main.recommendations import  transformPrefs, calculateSimilarItems, getRecommendedItems, topMatches
from main.models import Rating, Book, User
from main.forms import UserForm, BookForm

from django.db.models import Avg


# Funcion que carga en el diccionario Prefs todas las puntuaciones de usuarios a peliculas. Tambien carga el diccionario inverso y la matriz de similitud entre items
# Serializa los resultados en dataRS.dat

def loadDict():
    Prefs={}   # matriz de usuarios y puntuaciones a cada a items
    shelf = shelve.open("dataRS.dat")
    ratings = Rating.objects.all()
    for ra in ratings:
        user = int(ra.user.id)
        itemid = ra.book.ISBN
        rating = float(ra.ratingValue)
        Prefs.setdefault(user, {})
        Prefs[user][itemid] = rating
    shelf['Prefs']=Prefs
    shelf['ItemsPrefs']=transformPrefs(Prefs)
    shelf['SimItems']=calculateSimilarItems(Prefs, n=10)
    shelf.close()

#  CONJUNTO DE VISTAS

def index(request): 
    return render(request,'index.html')


def populateDB(request):
    populateDatabase() 
    return render(request,'populate.html')


def loadRS(request):
    loadDict()
    return render(request,'loadRS.html')


#APARTADO A
def search(request):
    if request.method=='GET':
        form = UserForm(request.GET, request.FILES)
        if form.is_valid():
            idUser = form.cleaned_data['id']
            user = get_object_or_404(User, pk=idUser)
            return render(request,'ratedBooks.html', {'usuario':user})
    form=UserForm()
    return render(request,'search_user.html', {'form':form })

# Apartado B
def topThree(request):
    if request.method == 'GET':
        book = Book.objects.all()
        books = book.annotate(average_rating=Avg('rating__ratingValue')).order_by('average_rating')[:3]
        return render(request, 'topThreeBooks.html', {'books':books})
    

# APARTADO C
def similarBooks(request):
    book = None
    if request.method=='GET':
        form = BookForm(request.GET, request.FILES)
        if form.is_valid():
            idBook = form.cleaned_data['isbn']
            book = get_object_or_404(Book, pk=idBook)
            shelf = shelve.open("dataRS.dat")
            ItemsPrefs = shelf['ItemsPrefs']
            shelf.close()
            recommended = topMatches(ItemsPrefs, idBook, n=2)
            items=[]
            for re in recommended:
                item = Book.objects.get(ISBN=re[1])
                items.append(item)
            return render(request,'similarBooks.html', {'book': book,'books': items})
    form = BookForm()
    return render(request,'search_book.html', {'form': form})


# APARTADO D
def recommendedBooks(request):
    if request.method=='GET':
        form = UserForm(request.GET, request.FILES)
        if form.is_valid():
            idUser = form.cleaned_data['id']
            user = get_object_or_404(User, pk=idUser)
            shelf = shelve.open("dataRS.dat")
            Prefs = shelf['Prefs']
            SimItems = shelf['SimItems']
            shelf.close()
            rankings = getRecommendedItems(Prefs, SimItems, int(idUser))
            recommended = rankings[:2]
            items = []
            for re in recommended:
                item = Book.objects.get(pk=re[1])
                items.append(item)
            return render(request,'recommendationItems.html', {'user': user, 'items': items})
    form = UserForm()
    return render(request,'search_user.html', {'form': form})

practicaRecSysG2/main/templates/bookRatedByUsers.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<section>
<h1> Users who rating this book: {{book.ISBN}}</h1>
{% for user in users %}
<ul>
<li> ID: {{user.id}} </li>
<li> Edad: {{user.age}}</li>
<li> Location: {{user.location}} </li>
</ul>
<br/>
{% empty %}
<h2> Any user rated this book </h2>
{% endfor %}
</section>
</body>
</html>

practicaRecSysG2/main/templates/header.html
<header>
<nav>
	<ul>
		<li><a href="/">Home</a></li>
		<li><a href="/populate">Populate database</a></li>
		<li><a href="/loadRS">Load Recommender System data</a></li>
		<li><a href="/search">Search rated books by a user</a></li>
		<li><a href="/similarBooks">Similar books from a specific book</a></li>
		<li><a href="/recommendedBooks">Recommend two books to a user</a></li>
		<li><a href="/topThree">Top three books</a></li>
	</ul>
</nav>
</header>

practicaRecSysG2/main/templates/index.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<h1>Welcome to Recommender System for Book-Crossing!!!</h1>
</body>
</html>

practicaRecSysG2/main/templates/loadRS.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<h1>Data loaded for the recommendation system</h1>
</body>
</html>

practicaRecSysG2/main/templates/populate.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<h1>Database loaded</h1>
</body>
</html>

practicaRecSysG2/main/templates/ratedBooks.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<section>
<h1>Books and ratings for userid {{usuario.id}}</h1>
{% for rating in usuario.rating_set.all %}
<ul>
<li>Book ISBN: {{rating.book.ISBN}} </li>
<li>Book title: {{rating.book.title}} </li>
<li>Book Rating: {{rating.ratingValue}} </li>
</ul>
<br/>
{% empty %}
<h2> User has not rated any book </h2>
{% endfor %}
</section>
</body>
</html>

practicaRecSysG2/main/templates/recommendationItems.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<h1>Recommended books for the UserID: {{user.id}}</h1>
{% for item in items %}
<ul>
<li>ISBN: {{item.ISBN}}</li>
<li>Title: {{item.title}}</li>
<li>Author: {{item.author}}</li>
</ul>
{% empty %}
<h2> Insufficient user data </h2>
{% endfor %}
</body>
</html>

practicaRecSysG2/main/templates/search_book.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}

<h1>Search Book</h1>
<form id='form' method='get' action=''>
{{form.as_p}}
<p><input type='submit' value='Confirm'/></p>
</form>

</body>
</html>

practicaRecSysG2/main/templates/search_user.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}

<h1>Search user</h1>
<form id='form' method='get' action=''>
{{form.as_p}}
<p><input type='submit' value='Confirm'/></p>
</form>

</body>
</html>

practicaRecSysG2/main/templates/similarBooks.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<section>
<h1>Two books more like to {{book.ISBN}} are:</h1>
<l>
{% for b in books %}
<li>{{b.ISBN}}</li>
<li>{{b.title}}</li>
<li>{{b.author}}</li>
<br />
{% endfor %}
</l>
</section>
</body>
</html>

practicaRecSysG2/main/templates/topThreeBooks.html
<html>
<head>
<title>Recommender System Book-Crossing</title>
</head>
<body>
{% include 'header.html' %}
<h1>Top Three books</h1>
{% for book in books %}
<ul>
<li>ISBN: {{book.ISBN}}</li>
<li>Title: {{book.title}}</li>
<li>Author: {{book.author}}</li>
</ul>
{% empty %}
<h2> Error al mostrar los libros </h2>
{% endfor %}
</body>
</html>